// `colorette` replacement: no ANSI colors inside the JVM (Maven does its own log formatting).
const identity = (s) => String(s);
export const options = { enabled: false };
export const isColorSupported = false;
export function createColors() { return colors; }
export const reset = identity;
export const bold = identity;
export const dim = identity;
export const italic = identity;
export const underline = identity;
export const inverse = identity;
export const hidden = identity;
export const strikethrough = identity;
export const black = identity;
export const red = identity;
export const green = identity;
export const yellow = identity;
export const blue = identity;
export const magenta = identity;
export const cyan = identity;
export const white = identity;
export const gray = identity;
export const bgBlack = identity;
export const bgRed = identity;
export const bgGreen = identity;
export const bgYellow = identity;
export const bgBlue = identity;
export const bgMagenta = identity;
export const bgCyan = identity;
export const bgWhite = identity;
export const blackBright = identity;
export const redBright = identity;
export const greenBright = identity;
export const yellowBright = identity;
export const blueBright = identity;
export const magentaBright = identity;
export const cyanBright = identity;
export const whiteBright = identity;
export const bgBlackBright = identity;
export const bgRedBright = identity;
export const bgGreenBright = identity;
export const bgYellowBright = identity;
export const bgBlueBright = identity;
export const bgMagentaBright = identity;
export const bgCyanBright = identity;
export const bgWhiteBright = identity;
const colors = { reset, bold, dim, italic, underline, inverse, hidden, strikethrough, black, red, green, yellow, blue, magenta, cyan, white, gray, bgBlack, bgRed, bgGreen, bgYellow, bgBlue, bgMagenta, bgCyan, bgWhite, blackBright, redBright, greenBright, yellowBright, blueBright, magentaBright, cyanBright, whiteBright, bgBlackBright, bgRedBright, bgGreenBright, bgYellowBright, bgBlueBright, bgMagentaBright, bgCyanBright, bgWhiteBright };
export default { options, isColorSupported, createColors, ...colors };
