package net.mwalser.openapi.toolkit.mojo

import org.apache.maven.plugin.logging.Log
import org.junit.jupiter.api.Test
import java.lang.reflect.Proxy
import kotlin.test.assertEquals

class MavenJsLogTest {
    private val entries = mutableListOf<String>()

    /** A Maven log that records `level: line`; every level is enabled. */
    private val log = Proxy.newProxyInstance(Log::class.java.classLoader, arrayOf(Log::class.java)) { _, method, args ->
        if (method.name.startsWith("is")) true else { entries += "${method.name}: ${args[0]}"; null }
    } as Log

    @Test
    fun `problem lines carry their own severity, the rest the level of the block`() {
        val stylish = """
            openapi.yaml:
              13:5  error    security-defined        Every operation should have security defined.
              22:7  warning  operation-4xx-response  Operation must have at least one 4XX response.

            < 1 more problem hidden > increase with openapi.toolkit.maxProblems
        """.trimIndent()

        MavenJsLog.problems(log, stylish, MavenJsLog.Level.ERROR)

        assertEquals(
            listOf(
                "error: openapi.yaml:",
                "error:   13:5  error    security-defined        Every operation should have security defined.",
                "warn:   22:7  warning  operation-4xx-response  Operation must have at least one 4XX response.",
                "error: ",
                "error: < 1 more problem hidden > increase with openapi.toolkit.maxProblems",
            ),
            entries,
        )
    }

    @Test
    fun `a file header takes the highest severity of its rows`() {
        val stylish = """
            openapi.yaml:
              23:5  error    no-unresolved-refs      Can't resolve ${'$'}ref
              29:7  warning  operation-4xx-response  Operation must have at least one 4XX response.

            paths/pets.yaml:
              1:1   warning  security-defined  Every operation should have security defined.
        """.trimIndent()

        MavenJsLog.problems(log, stylish, MavenJsLog.Level.ERROR)

        assertEquals(
            listOf(
                "error: openapi.yaml:",
                "error:   23:5  error    no-unresolved-refs      Can't resolve ${'$'}ref",
                "warn:   29:7  warning  operation-4xx-response  Operation must have at least one 4XX response.",
                "error: ",
                "warn: paths/pets.yaml:",
                "warn:   1:1   warning  security-defined  Every operation should have security defined.",
            ),
            entries,
        )
    }

    @Test
    fun `a codeframe block takes the severity of its trailer`() {
        val codeframe = """
            [1] openapi.yaml:23:5 at #/paths/~1owners

            Can't resolve ${'$'}ref

            23 |   ${'$'}ref: paths/owners.yaml
               |   ^^^

            Error was generated by the no-unresolved-refs rule.

            Reference: https://redocly.com/docs/cli/rules/oas/no-unresolved-refs


            [2] openapi.yaml:29:7 at #/paths/~1pets/get/responses

            Operation must have at least one 4XX response.

            29 | responses:
               | ^^^^^^^^^

            Warning was generated by the operation-4xx-response rule.

            Reference: https://redocly.com/docs/cli/rules/oas/operation-4xx-response
        """.trimIndent()

        MavenJsLog.problems(log, codeframe, MavenJsLog.Level.ERROR)

        val levels = entries.map { it.substringBefore(':') }
        assertEquals(List(12) { "error" } + List(10) { "warn" }, levels)
        assertEquals("warn: [2] openapi.yaml:29:7 at #/paths/~1pets/get/responses", entries[12])
        assertEquals("warn: 29 | responses:", entries[16])
    }

    @Test
    fun `summary rows carry their own severity`() {
        MavenJsLog.problems(log, "error   no-unresolved-refs: 1\nwarning security-defined: 4\n", MavenJsLog.Level.ERROR)
        assertEquals(listOf("error: error   no-unresolved-refs: 1", "warn: warning security-defined: 4"), entries)
    }

    @Test
    fun `other formats are logged at the level of the block`() {
        MavenJsLog.problems(log, "| 13:5 | error | security-defined |\n", MavenJsLog.Level.WARN)
        assertEquals(listOf("warn: | 13:5 | error | security-defined |"), entries)
    }

    @Test
    fun `blank output logs nothing`() {
        MavenJsLog.problems(log, "\n", MavenJsLog.Level.ERROR)
        assertEquals(emptyList(), entries)
    }
}
