package net.mwalser.openapi.toolkit.mojo

import net.mwalser.openapi.toolkit.redocly.JsLog
import org.apache.maven.plugin.logging.Log

/** Routes output of the JavaScript side to the Maven log, one log entry per line. */
class MavenJsLog(private val log: Log) : JsLog {

    enum class Level(internal val emit: Log.(CharSequence) -> Unit) {
        DEBUG(Log::debug),
        INFO(Log::info),
        WARN(Log::warn),
        ERROR(Log::error),
    }

    override fun output(message: String) = lines(message, log::info)

    override fun info(message: String) = lines(message, log::info)

    override fun warn(message: String) = lines(message, log::warn)

    override fun error(message: String) = lines(message, log::error)

    override fun debug(message: String) {
        if (log.isDebugEnabled) lines(message, log::debug)
    }

    companion object {
        /** Logs a multi-line text at one level. */
        fun block(log: Log, text: String, level: Level) = lines(text) { level.emit(log, it) }

        /**
         * Logs formatted problems at the severity the format states. Stylish rows (`13:5  error  rule-id ...`) and
         * summary rows (`error  rule-id: 1`) carry their own; a codeframe block names its severity in the trailer
         * (`Warning was generated by the ... rule.`). File headers, code frames and blank lines take the highest
         * severity of their block, which starts at a stylish header (`path:`) or a codeframe index
         * (`[2] path:line:col ...`). Formats without such markers are logged at [level].
         */
        fun problems(log: Log, text: String, level: Level) {
            if (text.isBlank()) return
            val lines = text.trimEnd().lines().map { it.trimEnd() }
            val levels = arrayOfNulls<Level>(lines.size)
            var start = 0
            fun flush(end: Int) {
                val block = (start until end).mapNotNull { levels[it] }.maxOrNull() ?: level
                for (i in start until end) if (levels[i] == null) levels[i] = block
            }
            lines.forEachIndexed { i, line ->
                if (i > start && BLOCK_START.matches(line)) {
                    flush(i)
                    start = i
                }
                levels[i] = SEVERITY.find(line)?.let { match ->
                    val word = match.groupValues.drop(1).first { it.isNotEmpty() }.lowercase()
                    if (word == "error") Level.ERROR else Level.WARN
                }
            }
            flush(lines.size)
            lines.forEachIndexed { i, line -> levels[i]!!.emit(log, line) }
        }

        private val SEVERITY = Regex(
            """^(?:\s*\d+:\d+\s+(error|warning)\b|(error|warning)\s+\S+:\s*\d+$|(Error|Warning) was generated by the .+ rule\.$)""",
        )
        private val BLOCK_START = Regex("""\S+:|\[\d+\] \S.*""")

        private fun lines(text: String, emit: (String) -> Unit) =
            text.trimEnd().lineSequence().map { it.trimEnd() }.forEach(emit)
    }
}
